> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- np.concatenate
- np.average
- np.round
- np.add
- np.zeros

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [ ]:
function1 = np.concatenate  
function2 = np.average
function3 = np.round
function4 = np.add
function5 = np.zeros

## Function 1 - np.concatenate

Join a sequence of arrays along an existing axis

In [3]:
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Join a sequence of arrays along an existing axis

In [8]:
arr1 = [[1, 2, 9], 
        [3, 4., 0]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  9.,  5.,  6.,  7.],
       [ 3.,  4.,  0.,  8.,  9., 10.]])

Join a sequence of arrays along an existing axis

In [9]:
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

arr1 and arr2 has different size

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 2 - np.average

Compute the weighted average along the specified axis.

In [5]:
np.average(arr1, axis=0)

array([2., 3.])

In [6]:
arr6 = [
    [1, 2, 3],
    [1, 4, 5],
    [1, 3, 6]
]
np.average(arr6, axis = 0, weights = [1, 0, 1])

array([1. , 2.5, 4.5])

In [7]:
np.average(arr6, axis = 0, weights = [0, 0, 0])

ZeroDivisionError: Weights sum to zero, can't be normalized

The sum of weight must be greater than 0 since you cannot devide something with zero.

There are many staistics applications, np.average is just one of them, these are really useful in almost anything.



In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 3 - np.round

Round an array to the given number of decimals.

In [11]:
# Example 1
arr = np.array([40, 30.5123, -0.2134])
arr1 = np.round(arr) # Rounding to the nearest whole number
arr1

array([40., 31., -0.])

round the array

In [15]:
# Example 2
arr4 = np.round(arr,decimals = 4) 
arr4

array([40.    , 30.5123, -0.2134])

Rounding up to 4 decimals.

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
np.round(arr, out = 1)


TypeError: output must be an array

output must be an array, change 1 to array 

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "carllam23/numpy-array-operations-b7a63" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/carllam23/numpy-array-operations-b7a63


'https://jovian.ai/carllam23/numpy-array-operations-b7a63'

## Function 4 - np.add

Add arguments element-wise

In [29]:
# Example 1 - working
np.add(1.0, 4.0)

5.0

add 1 and 4

In [28]:
# Example 2 - working
np.add(arr1,1)

array([41., 32.,  1.])

add 1 to the array

In [30]:
# Example 3 - breaking (to illustrate when it breaks)
np.add(arr1,1, out = 1)

TypeError: return arrays must be of ArrayType

return arrays must be of ArrayType, change out = 1 to out = array 7

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 5 - np.zeros

Return a new array of given shape and type, filled with zeros.

In [31]:
# Example 1 - working
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

return an array with 3 columns and 3 rows, fill with 0

In [32]:
# Example 2 - working
np.zeros(5)

array([0., 0., 0., 0., 0.])

return an array with 5 columns

In [33]:
# Example 3 - breaking (to illustrate when it breaks)
np.zeros(-1,-1)

TypeError: Cannot interpret '-1' as a data type

can't return array with -1 rows and columns, change it to positive number

In [28]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>